collections:
  /en/:
    permalink: /en/{slug}/
    template: index-en
    filter: "tag:hash-en"
  /cn/:
    permalink: /cn/{slug}/
    template: index-cn
    filter: "tag:hash-cn"

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
